### ISSUE TITLE
Comments don't work

### ISSUE THREAD

**Issue by deemeetree** [CyberCRI/KnowNodes#129]
http://www.libreop.us/connection/3fd4cab6-ca4e-4907-a958-3fcc297aa0c1 

Trying to leave a comment here, doesn't submit.

**Comment by Garbash** [comment]
checked, comments work, but I can see there is not button disable after
submit, which made it submit several times the same comment. I'm on it.

On Fri, Nov 15, 2013 at 1:47 PM, Dmitry Paranyushkin <
notifications@github.com> wrote:

> http://www.libreop.us/connection/3fd4cab6-ca4e-4907-a958-3fcc297aa0c1
> 
> Trying to leave a comment here, doesn't submit.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/CyberCRI/KnowNodes/issues/129
> .

## 

Get some insight of what makes me tick:
My twitter https://twitter.com/#!/garbash
Knownodes mailing list https://groups.google.com/forum/#!forum/knownodes

Dor Garbash
108 Rue du faubourg du temple, Paris 75011
+33-652919878

**Comment by deemeetree** [comment]
In general could be nice to add disabled and maybe some sort of spinning wheel dialogue on every button, so that the user sees that something is being done.
