### ISSUE TITLE
Add share by email to share button

### ISSUE THREAD

**Issue by Garbash** [CyberCRI/KnowNodes#136]

**Comment by deemeetree** [comment]
I'd simply add facebook integration with the send button: 
https://developers.facebook.com/docs/plugins/send-button/

**Comment by Garbash** [comment]
It's a good idea is to implement both, some people really hate facebook and
should have another option.

On Thu, Nov 21, 2013 at 10:41 PM, Dmitry Paranyushkin <
notifications@github.com> wrote:

> I'd simply add facebook integration with the send button:
> https://developers.facebook.com/docs/plugins/send-button/
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/CyberCRI/KnowNodes/issues/136#issuecomment-29027337
> .

## 

Get some insight of what makes me tick:
My twitter https://twitter.com/#!/garbash
Knownodes mailing list https://groups.google.com/forum/#!forum/knownodes

Dor Garbash
108 Rue du faubourg du temple, Paris 75011
+33-652919878
