### ISSUE TITLE
Login through facebook in local version sends you to Knownodes live version on the cloud!

### ISSUE THREAD

**Issue by Garbash** [CyberCRI/KnowNodes#21]
It's pretty dangerous this bug as coders can inadvertedly add test data into the production database!

**Comment by liadmagen** [comment]
No, they can't.
And no, it's not a bug.

Facebook need a url to return to after the login is performed (and Google
as well).
The can't redirect you to localhost.

**Comment by drpepper** [comment]
Perhaps you could disable 3rd-party login on localhost (or in "development" configuration). It is unexpected behavior, even if there is no way around it.
