### ISSUE TITLE
On-the-fly Wikinode creation takes too much time

### ISSUE THREAD

**Issue by couzic** [CyberCRI/KnowNodes#23]
When a user tries to create a new Relation between an existing Resource and a Wikipedia article, what I do from the client is : 
1. Create a Wikinode
   - Send a POST request to /knownodes/wikinode with the title of the Wikipedia article to link
   - Use the returned Wikinode's KN_ID (wheter already exists or created on-the-fly)
2. Create the Relation between the currently browsed Resource and the Wikinode

The problem I get when the Wikinode hasn't been already created is that it takes a very long time to create it. In effect, it disrupts the user experience.

I'm not sure why it takes so long, is it because we also create many other related Wikinodes ?

Anyway, we should find a way to return the query made to the /wikinode endpoint much faster. All we need from the client is the created node's KN_ID, so I'm pretty sure we can find an easy way to optimize that. Node.js is asynchronous by nature, so we should be able to start a new parallel process/thread and let it do all the heavy stuff while we return the newly created node.

That is just my naïve vision of the problem, I'm sure you guys will have better insight so I'm waiting for your ideas.

**Comment by drpepper** [comment]
It takes so long to create a wikinode becuase there are a number of web and DB requests going on:
1. To check that the article exists on Wikipedia
2. To check that if the node exists in the DB
3. To get the first paragraph
4. To get internal links
5. To get external links
6. To get backlinks
7. A DB request to see if a node already exists for each link found in steps 4, 5, and 6
8. A DB request to create a connection for each existing node found in step 7

Furthermore all Wikipedia requests are queued instead of done in parallel, in order to avoid getting banned.

There are certainly a number of ways to speed up this process!

**Comment by couzic** [comment]
OK, so would it be practical to make the user wait for the end of step 3,
until we create the node, and that the rest would be completed as a background
process after the server has answered the HTTP request ?

Again, I'm kind of shooting in the dark here, and I'd be happy to be
enlightened !

## 

Mikael Couzic

84, rue Vergniaud
75013 Paris
09 54 90 02 55
06 51 17 97 83

2013/6/19 Jesse Himmelstein notifications@github.com

**Comment by drpepper** [comment]
That's actually the way it used to work, but when I did batch importing of Wikinodes the server couldn't handle a backlog of any more than 30-40 requests before it just stopped working! So I made it wait until the end, so at least it keeps the importer at the correct pace.

A better solution might be to have the wikinode creation done in a background process.

**Comment by couzic** [comment]
OK, I start to get it.
Just thinking, do we really need both scenarios (batch import and
user-created wikinode) to use the same endpoint ? We could have two
separate URLS (for example, /wikinode and /wikinode-batch) that would each
implement a separate strategy.
The /wikinode endpoint would be more unstable, but we're not very likely to
experience the kind of load that would make it crash, am I right ?

## 

Mikael Couzic

84, rue Vergniaud
75013 Paris
09 54 90 02 55
06 51 17 97 83

2013/6/19 Jesse Himmelstein notifications@github.com

**Comment by drpepper** [comment]
That would work too, I suppose. I have to say that I slightly prefer the
background process idea because it could also do things like update the
relevance of newly inserted nodes, but it would probably be more work as
well.

2013/6/19 Mikael Couzic notifications@github.com

**Comment by couzic** [comment]
I agree, but I don't see how you can answer the HTTP call with the newly
created node's KN_ID if all the creation process is delegated to a
background process. Or am I missing something ?

## 

Mikael Couzic

84, rue Vergniaud
75013 Paris
09 54 90 02 55
06 51 17 97 83

2013/6/19 Jesse Himmelstein notifications@github.com

**Comment by drpepper** [comment]
Oh, I was suggesting that you change the API call to simply return the new
node, without adding any connections to it. Then a background process would
pick up the newly created nodes and connect them and calculate the
relevancies.

2013/6/19 Mikael Couzic notifications@github.com

**Comment by couzic** [comment]
OK then we agree, that's kind of what I was trying to express in an earlier
message, now I realize it wasn't very clear :

"OK, so would it be practical to make the user wait for the end of step 3,
until we create the node, and that the rest would be completed as a background
process after the server has answered the HTTP request ?"

So how should we do it (and who =D ) ?

## 

Mikael Couzic

84, rue Vergniaud
75013 Paris
09 54 90 02 55
06 51 17 97 83

2013/6/19 Jesse Himmelstein notifications@github.com

**Comment by couzic** [comment]
After discussing with Dor, we decided that for now we would just disable the creation of all the links. We don't have the time to do much more until we send the LinkedUp application.
