### ISSUE TITLE
Error in inputting connection between two wiki articles

### ISSUE THREAD

**Issue by Garbash** [CyberCRI/KnowNodes#59]
In development mode.
I've tried connection between "Jar" article to "Raj" article.
The two resources disappeared from the input interface( the connection remained intact)
Console shows the following error:
Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:3000/wiki/Jar
startID:  
Object
 endId:  
Object
 controllers.js:468
Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:3000/connections
Connection creation failed with error : 404 controllers.js:474
Error message : undefined 
Also,  server side console error:
POST /wiki 200 1875ms - 232b
POST /wiki 200 1912ms - 232b
INFO: Callback - EntityNotFound - No kn_Post found for KN_ID : undefined
POST /connections 404 340ms - 57b

**Comment by couzic** [comment]
Pushed correction : https://github.com/CyberCRI/KnowNodes/commit/8c7b4446953dd8bc7b6e63beffe4f0c0a8c3b449
